services:
  ollama:
    build:
      context: ./ollama
    container_name: ollama_server
    networks:
      - llm_network
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  python:
    build:
      context: ./python
    container_name: python_client
    depends_on:
      - ollama
    volumes:
      - ./python:/app
    networks:
      - llm_network
    working_dir: /app
    stdin_open: true
    tty: true


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - llm_network

networks:
  llm_network:
    driver: bridge

volumes:
  qdrant_data:
